version: "3"
services:
  flask:
    image: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./:/python-docker
    depends_on:
      - mysql
    networks:
      - clam-net
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - mysql_data1:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "flask_db"
      MYSQL_USER: "flask_user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306
    networks:
      - clam-net
volumes:
  mysql_data1:
    driver: local
networks:
  clam-net: